# Generated by Django 3.2.10 on 2021-12-13 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0004_auto_20211208_0409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotation',
            name='endX',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='annotation',
            name='endY',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='annotation',
            name='startX',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='annotation',
            name='startY',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='image',
            name='height',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='image',
            name='width',
            field=models.FloatField(),
        ),
    ]
